version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  web:
    build: .
    volumes:
      - .:/code
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: '127.0.0.1'
      POSTGRES_PORT: 5432
      POSTGRES_DB: mydatabase
    ports:
      - "8000:8000"
    depends_on:
      - db